### ISSUE TITLE
nmd

### ISSUE THREAD

**Issue by ShFFnqhCJ** [signalstickers/signalstickers#154]
nmd

**Comment by romainricard** [comment]
Hello @ShFFnqhCJ , was it a problem on your side, or did you really had to turn off privacybadger? I'm really interested in this kind of problems. Thanks!

**Comment by ShFFnqhCJ** [comment]
> Hello @ShFFnqhCJ , was it a problem on your side, or did you really had to turn off privacybadger? I'm really interested in this kind of problems. Thanks!

hey m8 my bad, what happened was it took too long to load and i thought it was the extension. turns out it wasn't, i just needed more patience (and coffee).

**Comment by romainricard** [comment]
No problem :+1: :coffee:
