### ISSUE TITLE
Can't add tags in Contribute form

### ISSUE THREAD

**Issue by romainricard** [signalstickers/signalstickers#175]
The field to add tags to a pack in `/contribute` seems broken.

> it kept giving me an error, even though I had everything separated with commas, tried making them strings with ' ' but didnt work either

> I can confirm that the form looks broken, I haven't been able to add tags either through the webpage. Even with a classic and clean comma-separated strings list like "foo, bar, baz", I always got an error telling me that I have to give a comma separated list of strings when I submit. I had to leave the field blank and add the tags by myself directly in the YML. I tried with Firefox firefox-esr 68.7.0esr-1 and Chromium chromium 81.0.4044.92-1.

I **can't** reproduce either with Firefox `68.7.0esr` or Chrome ` 81.0.4044.113` (Linux x64) .

**Comment by jakeattack77** [comment]
I think i just figured it out. The form seems to expect a space after the comma. When filling out the form originally based on the wording I thought it wouldn't like a space like that. This is on Firefox 75.0 64 bit


![image](https://user-images.githubusercontent.com/52475159/79398227-bbe46580-7f45-11ea-9972-ec0d32fadb58.png)

![image](https://user-images.githubusercontent.com/52475159/79398251-cef73580-7f45-11ea-95ec-07e19175b0ef.png)

**Comment by romainricard** [comment]
OK so in your case, it was the phrasing of the explanations that wasn't clear! Thank you for your feedback, you are right, we'll change the phrasing!
Still, @jvaubourg seems to have experimented it even with spaces after commas.
