### ISSUE TITLE
[missing tag] "a private sticker pack"

### ISSUE THREAD

**Issue by JanOstrowka** [signalstickers/signalstickers#185]
There is a missing "content: 'Original';" tag in the "[a private sticker pack](https://signalstickers.com/pack/26f539946b56a8a900083d5bfaca4e4d)"

**Comment by romainricard** [comment]
Fixed by https://github.com/signalstickers/signalstickers/commit/cab9a4867ae65d89d0d01778709bef6a2ba7f7c3, thank you @JanOstrowka  !

**Comment by JanOstrowka** [comment]
Thank you too
