### ISSUE TITLE
Sticker pack not conducive to family atmosphere

### ISSUE THREAD

**Issue by jeffcutsinger** [signalstickers/signalstickers#217]
Hi,

This sticker pack: https://signalstickers.com/pack/1267f0b4aeac05061adbf55084371561

Uses the word "retarded," which is widely regarded as a slur against people with mental disabilities.

**Comment by romainricard** [comment]
Hi, thanks for reporting it. I deleted it (https://github.com/signalstickers/signalstickers/commit/bad548f5ee8a25895738b217730950a6db901d30) for now, and I'll remake it without the offensive title when I'll have the time.
