### ISSUE TITLE
Several NSFW sticker packs not labeled as NSFW

### ISSUE THREAD

**Issue by ML-Chen** [signalstickers/signalstickers#240]
Some sticker packs have NSFW stickers but are not tagged as NSFW and should be:
- [Jaime](https://signalstickers.com/pack/0a042227bb1a4fc6894b7bc15bc8a557), due to the sticker labeled 😉
- [Very Very GAY @TuristasTV](https://signalstickers.com/pack/532c8c4a66eef92188834f7a1f03417e), due to the banana sticker labeled 😍
- [Super Chad](https://signalstickers.com/pack/1690c60ad63d8a331fa08f70a667fc75)
- [Unicorn](https://signalstickers.com/pack/a45e52949071db8a25140938417f1dc8) due to the sticker labeled 🖕
- [x-files](https://signalstickers.com/pack/d2152594b5ad172e2878709467378ce7) might be due to the sticker labeled 🖕
- [Big words](https://signalstickers.com/pack/1dcc964b351ac1f7c8552f1688c62995) might also be due to the expletive in the sticker labeled 😖, and similarly [Shakespeare](https://signalstickers.com/pack/a4d0869106f67799e09a89362479b393)'s 🙄. It depends on whether you consider profanity to be NSFW.
- [Linus Torvalds](https://signalstickers.com/pack/c6b83611dd5076fa5f24a8d42c40dd6a) might be due to the sticker labeled 😏 with the text "Software is like sex. It's better when it's free." and similarly [Titanic](https://signalstickers.com/pack/e1e81e585e2dd27f054d54cd73e6fef6)'s "I just had sex."

**Comment by romainricard** [comment]
Thank you very much for your detailed message review!

- **Jaime**: "innocent-looking" stickers (= _can be mistaken by children for innocent images_) but contains strong sexual references, so I'll mark it NSFW
- **Very Very GAY @TuristasTV**: obviously NSFW
- **Super Chad**: meme and does not contains strong sexual references, so not NSFW
- **Unicorn**: does not contains strong sexual references BUT as "unicorn" can easily be searched for by children, I'll mark it NSFW.
- **x-files**: does not contains strong sexual references, so not NSFW
- **Big word**: I don't consider profanity NSFW
- **Shakespeare**: I don't consider profanity NSFW
- **Linus Torvalds**: is it an authentic citation, I don't consider it NSFW
- **Titanic**: it is a meme and does not contains strong sexual references, so not NSFW


Thanks again for bringing these to my attention!
