### ISSUE TITLE
SSL Certificate Expired for cdn-ca.signal.org

### ISSUE THREAD

**Issue by xumx** [signalstickers/signalstickers#254]
Seems like 
SSL Certificate of cdn-ca.signal.org has just expired today. 

Example:
https://cdn-ca.signal.org/stickers/cd5386b013e92baa1929f840ee1da573/full/47

Impact:
https://signalstickers.com/ is completely unusable.

**Comment by romainricard** [comment]
Thank you for the report. We are aware of the problem, and are working on a fix! :wrench:

**Comment by romainricard** [comment]
Signal reacted before our fix, so it is, well, fixed! :tada:
