### ISSUE TITLE
Sticker pack error - Milk and Mocha

### ISSUE THREAD

**Issue by Githubuxer** [signalstickers/signalstickers#282]
The following sticker pack doesn't have a preview icon for the horizontal sticker row and doesn't show up when you click on the + icon to show installed sticker packs:

https://signalstickers.com/pack/2abaece7b68e04ff4a7d09448271a140

(No preview image)
![image](https://user-images.githubusercontent.com/62911518/91634488-d97b0e80-e9be-11ea-9ac1-46b77ae54812.jpeg)

Not showing as installed 
![image](https://user-images.githubusercontent.com/62911518/91634513-fd3e5480-e9be-11ea-81f1-75fe153edcb0.jpeg)

**Comment by romainricard** [comment]
Thanks for the report! Can you give us more details about your configuration? I can't reproduce on Android (4.70.2 and previous) or Linux Desktop app (v1.35.1-beta.1 and previous).

 
<details><summary>Android screenshot</summary>

![mmi1](https://user-images.githubusercontent.com/7778898/91636003-76f53300-e9fd-11ea-929f-3ceddbed733f.jpeg)
![mmi2](https://user-images.githubusercontent.com/7778898/91636004-778dc980-e9fd-11ea-87de-f279870c1f70.jpeg)
</details>


 
<details><summary>Linux app screenshot</summary>

![image](https://user-images.githubusercontent.com/7778898/91636042-df441480-e9fd-11ea-80fd-8df8539f4c71.png)

![image](https://user-images.githubusercontent.com/7778898/91636048-e5d28c00-e9fd-11ea-84eb-ccf370e7a5da.png)

</details>

**Comment by Githubuxer** [comment]
Thanks for following up, I am running latest iOS release on iPhone 6S.

**Comment by Githubuxer** [comment]
All the other animated sticker packs install and display correctly

**Comment by romainricard** [comment]
I'll take a look, but I don't see why this pack would be different from the other animated packs.
Have you tried uninstalling the pack from a Desktop app, then re-installing it again? The problem might be caused by an installation bug

**Comment by Githubuxer** [comment]
I just uninstalled and reinstalled via the desktop app and it works great on desktop, but on iOS, the icon the horizontal sticker pack selection row is still blank and the sticker pack does not show up under installed stickers.

**Comment by romainricard** [comment]
I see no problem while checking the content of the pack, and I don't have an iPhone to test. If someone with an iPhone can give us more insights, that would be appreciated!

**Comment by darkobits** [comment]
I can confirm this is happening on iOS 13.6.1. [Video](https://app.blackhole.run/#e89onv4Ino1JmUvS6hbemuhkDShFdQ95r3xJUh75kcnu).

I should also mention the flicker in individual stickers is not a bug in the video, and occurs with several animated stickers on iOS devices.

**Comment by romainricard** [comment]
There's some weird compression going on there! 
![image](https://user-images.githubusercontent.com/7778898/91975100-29d7d080-ed1f-11ea-82a0-60d4a80afa78.png)

For the flickering issue, a naive guess is that this might be due to the GIF handling on iOS/in the image viewer used by Signal. Did you see the same problem with GIFs from Giphy?

Still no clues about the miniature. The miniature seems defined in the pack correctly. I might end up re-doing the pack, but I'd like to understand what went wrong!

**Comment by romainricard** [comment]
Another user that previously had this issue informed me that the latest Signal update fixed it. Can you confirm @darkobits @Githubuxer ?

**Comment by Githubuxer** [comment]
Looks like it’s just the Pusheen collection that is flickering right now in the horizontal row, and the larger preview section.

**Comment by adam-sroka** [comment]
Running Signal 3.17.3 on iOS 14.0 (18A373) with an iPhone 6s here.

Apart from the flickering, everything seems to be running fine both in light mode:

![light](https://user-images.githubusercontent.com/45038919/93886537-13e17e00-fcd5-11ea-9943-f9ec75d35069.gif)

and in dark mode as well:

![dark](https://user-images.githubusercontent.com/45038919/93886639-3a9fb480-fcd5-11ea-81da-cf3349ac581f.gif)

The flickering is quite inconsistent, usually doesn't happen on a fresh open of the app, but sometimes does when coming back from other apps, with Signal being open in the background.

To me, this does not seem like a big issue, so I'd consider calling it fixed @romainricard, but it might be that I'm just lacking some perfectionism in this aspect 😄 !

**Comment by romainricard** [comment]
Thanks a lot for the feedback @adam-sroka ! I think you are right. Moreover, Signal [is about to release the official version of animated stickers](https://community.signalusers.org/t/please-add-animated-stickers-like-in-telegram/12158/14?u=f00b4r), with aPNG. Maybe I'll redo the _old_ animated packs with aPNG. I'll close for now, thanks to everybody involved!

**Comment by adam-sroka** [comment]
> Thanks a lot for the feedback @adam-sroka ! I think you are right. Moreover, Signal [is about to release the official version of animated stickers](https://community.signalusers.org/t/please-add-animated-stickers-like-in-telegram/12158/14?u=f00b4r), with aPNG. Maybe I'll redo the _old_ animated packs with aPNG. I'll close for now, thanks to everybody involved!

Thanks a lot for the info! I was about to try creating some Milk and Mocha animated sticker sets myself, and so I compiled about 50 of their gifs from [Tenor](https://tenor.com/). I'm not sure about the copyright aspects of that, but if you'd like to use some of them, they're [here](https://send.tresorit.com/a#wTWKyLvYYmEvmRTTVkNJtw).
