### ISSUE TITLE
South park sticker pack stickers not visible on IOS

### ISSUE THREAD

**Issue by koponomarenko** [signalstickers/signalstickers#292]
All stickers form this striker pack https://signalstickers.com/pack/5bab515e5965ceea230a5e79598c55ac are not visible on IOS when sent from Android. Thought it works vise versa.

IOS version 13.7
Android version 10

**Comment by romainricard** [comment]
I can reproduce with a friend's iPhone. I see that you opened [this issue on Signal-iOS](https://github.com/signalapp/Signal-iOS/issues/4562), I'll let Signal dev figure it out, as I'm not the author of the pack, and this is likely a bug on Signal side. Thanks!
