### ISSUE TITLE
Why include sticker packs that promote other messengers?

### ISSUE THREAD

**Issue by Cerberus0** [signalstickers/signalstickers#336]
While such packs may be fun, it doesn't feel right for signalstickers.com to include packs that are explicitly meant for the promotion of other messengers. For example, this one is meant to promote Telegram:

* https://signalstickers.com/pack/1821dabd93b9a5f2feaf9f303042453a

**Comment by romainricard** [comment]
I remember this pack. There are some interesting stickers, not directly promoting Telegram, that can be used to promote private messenger rather than Whatsapp.
