### ISSUE TITLE
Some tags are not showing up

### ISSUE THREAD

**Issue by Cerberus0** [signalstickers/signalstickers#341]
The tags that were added with https://github.com/signalstickers/signalstickers/pull/335 do not appear to be showing up on signalstickers.com. For example, this pack should now include the "WhatsApp" tag:

https://signalstickers.com/pack/08f7c55133380928517f9afb0c3c1eca

**Comment by romainricard** [comment]
Thanks for the report. It seems like there's a problem with our CI. Caches are used but we can't clear them for now.

**Comment by romainricard** [comment]
I've managed to clear the caches. Tags are now up, thanks again!
