### ISSUE TITLE
Incorrectly named and tagged Moomin sticker pack

### ISSUE THREAD

**Issue by Cerberus0** [signalstickers/signalstickers#361]
This sticker pack is both named and tagged incorrectly:

* https://signalstickers.com/pack/70ce21c56d10da385a2d4cbd01b0a598

The subject does not represent a cow or any other animal. It's a fictional character called a Moomin troll:

* https://en.wikipedia.org/wiki/Moomins

It belongs in the same category as these sticker packs:

* https://signalstickers.com/?s=tag%3Amoomin

**Comment by romainricard** [comment]
Thank you very much for the report! Indeed you are right. I've renamed the pack in https://github.com/signalstickers/signalstickers/commit/72251c5be4efbd0fc0ef3910d5dd66e6d31115a8.

> Note: as caches are still broken (see https://github.com/signalstickers/signalstickers/issues/341), the modification might not appear  right away.
