### ISSUE TITLE
Requesting removal of stickers

### ISSUE THREAD

**Issue by Arunkumar47** [signalstickers/signalstickers#490]
Someone Copied our stickers without our permission. We want you guys to remove from your site https://signalstickers.com/pack/9da172a7a5d078818a653f7bef3ec980

**Comment by romainricard** [comment]
Hello, can you please share the original source from these stickers, as well as a piece of evidence that would prove that you own them? I will then proceed to the removal. Thanks!

**Comment by Arunkumar47** [comment]
Hi Roman,

This is the app link which has source of the mentioned sticker pack
https://play.google.com/store/apps/details?id=com.stickers.tamilandastickers

And you can clearly see developer email in the playstore account is same as
mine - mail2arun1994@gmail.com

I request you to remove those sticker pack from your website. Thanks

Regards,
Arunkumar

**Comment by romainricard** [comment]
The pack has been removed.
