### ISSUE TITLE
Migrate to TravisCI

### ISSUE THREAD

**Issue by darkobits** [signalstickers/signalstickers#59]
Creating this as a todo item/reminder for @romainricard, as the original conversation took place [here](https://github.com/romainricard/signalstickers/pull/49#pullrequestreview-341659304).

This will allow us to properly run checks in PRs where the head branch is in a forked repository.

**Comment by romainricard** [comment]
> Note for the current CI: I had a build success with the current CI while merging https://github.com/romainricard/signalstickers/commit/21c824bd98de85fe1d79b6ed8e5d97b2aa898171, but the links to `app-xxx.js` in the built  `index.html` were still the old ones, so the website didn't load. I had to remove manually the `gh-pages` branch and push another commit. This might be worth investigating if migrate to TravisCI.

**Comment by romainricard** [comment]
Closed by https://github.com/signalstickers/signalstickers/pull/87, thank you!
