### ISSUE TITLE
code characters count exceeded 

### ISSUE THREAD

**Issue by shu-shi** [signalstickers/signalstickers#699]
Hello, I am new to the site. 
I tried pasting the generated YAML entry at the propose changes : Update stickers.yml but failed to do so because my code count has exceeded 50 characters, despite leaving only the first 2 lines of codes. 

Below was the generated YAML code i tried to add in: 

83994b4d12b5dac8469828a09609fb9c:
  key: 6792508d9624173542d9e186a4e82b63b14f5798e71efc2f11295d59082623da
  source: Piwio Studio Line
  tags:
    - Gojill
  animated: true

I was using the Safari browser on my mobile phone, iOS 14.3 (latest).  

Thank you for looking into the issue.

 ~ shu-shi

**Comment by romainricard** [comment]
Hi! Where did you try to add the YAML? You need to modify [stickers.yml](https://github.com/signalstickers/signalstickers/blob/master/stickers.yml), then open a Pull Request.

**Comment by darkobits** [comment]
@romainricard Sorry for the mixup here. @shu-shi was having some trouble with the Pull Request approach, so I asked them to just paste the YAML from the Contribute form in an Issue instead, and I was going to add the pack manually the next time I did a batch of PRs.

I didn't realize they were on mobile, but I can't imagine this process being anything less than incredibly tedious when done from a phone.

> failed to do so because my code count has exceeded 50 characters

I'm also unsure what this is referring to.

At any rate, I'm just going to get this pack added. I can additionally investigate potential issues with the Contribute process on iOS, but seeing as its going to be changing soon, it may not be worth it.

**Comment by romainricard** [comment]
I _think_ this 50 chars limitation could be the Github' commit message one. 

![image](https://user-images.githubusercontent.com/7778898/104786897-957e7f80-578e-11eb-8bf7-0768bec3f66c.png)
