### ISSUE TITLE
Incorrectly tagged Everyday Business Fish

### ISSUE THREAD

**Issue by SpazMahTazz** [signalstickers/signalstickers#835]
I created #651 - [Everyday Business Fish](https://signalstickers.com/pack/c4674f22e39da75ada26b08dddde4c80), however upon doing so I used the tag "Quang Inc" instead of "Quan Inc".

Being new to making stickers and creating Pull Requests, I don't know how to fix the tag, and I have looked for guidance. I hope submitting an issue will be okay. If not please let me know what needs to be done in the future.

Thanks.

**Comment by darkobits** [comment]
This should be fixed now. 😸
