### ISSUE TITLE
Duplicate packs

### ISSUE THREAD

**Issue by tl-pierre** [signalstickers/signalstickers#842]
Hi, 
During my research, I noticed 2 duplicate packs : 
- https://signalstickers.com/pack/045c16104bd99d0c8c13d9f9dcc63201 and https://signalstickers.com/pack/1134f259dbf082dcb5c4147ed0a12b2c

- https://signalstickers.com/pack/2f977990cc97776e3507f1f8c8ffa1b9 and https://signalstickers.com/pack/f4d5faaeac43f116d8e2ec84297a7424

Thank you for this great project :)

**Comment by romainricard** [comment]
Aaaaaaaand yep, these are duplicates! Thank you very much ! :+1:
