### ISSUE TITLE
Commercially sold stickers are listed on signalstickers.com

### ISSUE THREAD

**Issue by pjxiao** [signalstickers/signalstickers#845]
Hi,

I'm enjoying looking for stickers on signalstickers.com.

But, I found an enormous number of  stickers which were commercially sold.
Obviously, those sticker are intended to be freely distributed without any permission.

Though I'm not a contents holder or a lawyer, I fear that distributing those sticker may be harmful for original creators, or expose signalstickers.com to legal risks.
What do you think? Are there any plans to deny such stickers or add a contribution guideline?

Here are such stickers I found:

| signalstickers.com | Original |
|--|--|
| https://signalstickers.com/pack/e0c6fd4e0359f6890d13ad25830dfde3 | https://store.line.me/stickershop/product/1756/en |
| https://signalstickers.com/pack/321cbac49359cab5a6518bd5008b43d8 | https://store.line.me/stickershop/product/7714187/en |
| https://signalstickers.com/pack/7776c5d729999619cc6413df55c35e20 | https://store.line.me/stickershop/product/875/en |
| https://signalstickers.com/pack/5cec9a305a5f9d7f72f4b19df5f689f3 | https://store.line.me/stickershop/product/15906/en |
| https://signalstickers.com/pack/381565bffa14d0ed7b412fa17dbc9fb4 | https://store.line.me/stickershop/product/3147970/en |

**Comment by romainricard** [comment]
Hi @pjxiao,

Thanks for your message. I found a lot of stickers on Line that were freely available on other platforms (Telegram, etc.), so I guess this is just the business model of Line which requires that some stickers have to be paid for. We are attentive to takedown requests, and remove packs when a a content creator or rights holder asks for removal.

Thanks again!
