### ISSUE TITLE
Missing NSFW tag 

### ISSUE THREAD

**Issue by tl-pierre** [signalstickers/signalstickers#850]
Hi,
I think the NSFW tag is missing for this pack : https://signalstickers.com/pack/d89703d6f218c05be7bfe4028e8cf805
I saw it on Twitter, stickers are not blurred in the preview : https://twitter.com/signalstickers/status/1409568841622077441

Moreover, this pack seems a little problematic to me, there are at least 2 tendentious images in which there is a child. 

Thanks !

**Comment by romainricard** [comment]
Hello, sorry for the delay, I missed this issue!

I ask some fellow Hongkongers, and it seems that they are images from the Apple Daily. I'll add a NSFW tag tho.

Thanks for the report!
