### ISSUE TITLE
Upload Correct Eeveea Emote Pack version

### ISSUE THREAD

**Issue by montgomerysamantha** [signalstickers/signalstickers#852]
Hi, sorry but the rainbow emote for this pack is slightly different from the original Eeveea's Emotes pack, is it possible if you could replace that pack with this one? the first one uploaded is incorrect
Thank you!
New pack: https://signal.art/addstickers/#pack_id=dfe8a37d39e1f0fb1e7a8501ad850d2b&pack_key=980e461572217360772087376ad42efc166d0b2dcf1abe7ddc61b311ba5453c1

Old pack that needs updated / deleted and replaced, whatever works: https://signalstickers.com/pack/9e34aa3f379e83187708f7a2b1d67c3e

**Comment by romainricard** [comment]
Thanks, it has been replaced!

**Comment by montgomerysamantha** [comment]
Thanks! @romainricard 👍
