### ISSUE TITLE
Failure to preview sticker packs with empty author/by

### ISSUE THREAD

**Issue by mziehm** [signalstickers/signalstickers#863]
I noticed when trying to preview sticker not included on signalstickers.com yet, that the preview function fails with "invalid key", when the author/by field of the sticker pack is empty. Please consider if this also applies to other parts of the page.

Examples:
https://signal.art/addstickers/#pack_id=fa3e5cc818d6f42ef5ddd6939bd299bb&pack_key=8564c49aaee278882bcdb630ebe9ed292651d5170d026fc87b61059ff58bbcb7
https://signalstickers.com/pack/pack_id=fa3e5cc818d6f42ef5ddd6939bd299bb?key=8564c49aaee278882bcdb630ebe9ed292651d5170d026fc87b61059ff58bbcb7

https://signal.art/addstickers/#pack_id=45376cbcdf2e0f06f56851d59fcd64f8&pack_key=9bf13fc2d37340c2df20905986028e9c868a633898da6608458334bf80e67eec
https://signalstickers.com/pack/pack_id=45376cbcdf2e0f06f56851d59fcd64f8?key=9bf13fc2d37340c2df20905986028e9c868a633898da6608458334bf80e67eec

I think this is browser independent, but just to be sure:
Firefox 94.0 (64-bit) on Ubuntu 18.04 (64-bit) as well as Chromium Version 95.0.4638.69 (Official Build) on Ubuntu 18.04 (64-bit)

**Comment by romainricard** [comment]
Thanks for the report! I'll give it a look.

**Comment by darkobits** [comment]
These packs are, in fact, viewable on Signal Stickers. The correct URL format is:

`https://signalstickers.org/pack/<packId>?key=<packKey>`

The following URLs should work for you:

https://signalstickers.org/pack/fa3e5cc818d6f42ef5ddd6939bd299bb?key=8564c49aaee278882bcdb630ebe9ed292651d5170d026fc87b61059ff58bbcb7

https://signalstickers.com/pack/45376cbcdf2e0f06f56851d59fcd64f8?key=9bf13fc2d37340c2df20905986028e9c868a633898da6608458334bf80e67eec

Additionally, I'll improve our error handling for malformed pack IDs to better communicate what's going on.
