### ISSUE TITLE
[Removal request]

### ISSUE THREAD

**Issue by mziehm** [signalstickers/signalstickers#866]
Sticker Pack https://signalstickers.com/pack/e73fe32b39e048e6e0a6254971318cf4
is at the very least NSFW and not marked,
in my opinion it is also promoting hatred and violence and is insulting to people with Down syndrome - "Mongo" in German can be and is in the sticker used to degrade people with Down syndrome - so please consider remove this sticker pack.

**Comment by romainricard** [comment]
Sorry for the delay, I missed this Issue. I've removed the pack, thanks for reporting it!
