### ISSUE TITLE
Missing NSFW tag

### ISSUE THREAD

**Issue by tl-pierre** [signalstickers/signalstickers#867]
Hi,
I think the NSFW tag is missing for this pack : https://signalstickers.com/pack/d424f016421cf69d43db91d87cc4c5b9
Twitter post (not blurred) : https://twitter.com/signalstickers/status/1478310567081398283

Please also check if it doesn't go against the "contribution guidelines" (nazi symbols,WTC meme)

Thanks for your work!

**Comment by romainricard** [comment]
This pack goes against the contribution guidelines, and was approved by mistake. Thanks for reporting it quickly!
