### ISSUE TITLE
['Pack does not exists on Signal: wrong ID or key?'] error every time

### ISSUE THREAD

**Issue by tranh1987** [signalstickers/signalstickers#876]
['Pack does not exists on Signal: wrong ID or key?'] error every time attempting to upload stickers since a few days ago. 

Tried to upload multiple times with new keys.

Always the same error.

![Screenshot from 2022-04-01 20-22-53](https://user-images.githubusercontent.com/102797410/161236963-b347b9f8-c18c-4b49-9b8d-825c41b9f217.png)

**Comment by romainricard** [comment]
Yep, something was broken on our side. It should be fixed, thanks for the report!
