### ISSUE TITLE
 ['Pack does not exists on Signal: wrong ID or key?'] error every time

### ISSUE THREAD

**Issue by mdeguzis** [signalstickers/signalstickers#888]
Same as https://github.com/signalstickers/signalstickers/issues/876. Just tried this today multiple times.

['Pack does not exists on Signal: wrong ID or key?'] error every time attempting to upload stickers since a few days ago.

Tried to upload multiple times with new keys.

Always the same error.

**Comment by Fuchs** [comment]
Can reproduce, tried to add a pack twice, the error is oddly enough not given for the field where you add the sticker URL, but rather for the security / anti spam question

**Comment by romainricard** [comment]
Fixed by https://github.com/signalstickers/signalstickers-client/pull/13, thanks for the report!
