### ISSUE TITLE
['Pack does not exists on Signal: wrong id or key?'] 

### ISSUE THREAD

**Issue by PlayDohBear** [signalstickers/signalstickers#894]
Looks like this issue is still present. Not sure how to fix :3

**Comment by samho1234567** [comment]
![Signa_lScreenshot](https://user-images.githubusercontent.com/8604017/200015320-40eb712c-e344-4304-a46f-6ed0c315c1bd.jpg)

I had reached out to the admin of Signal Stickers, Romain, on Signal a few days ago. He replied that he would take a look, but there is no update until now...

**Comment by romainricard** [comment]
Fixed by https://github.com/signalstickers/signalstickers-client/pull/13, thanks for the report!
