### ISSUE TITLE
Add author website link to Fluffcorn sticker pack

### ISSUE THREAD

**Issue by ansonl** [signalstickers/signalstickers#895]
Hi, we submitted the Fluffcorn sticker pack which was accepted and available here: https://signalstickers.com/pack/bd27b4525f24f828a9cdfd5ccda5a124

However, the artist's website link was left out. Other stickers seem to have a info field for the author's website. 

Can our artist's link be added to the Fluffcorn sticker pack listing? The correct artist link is https://alishaliu.com/. For reference, our main repo is at https://github.com/Fluffcorn.

**Comment by romainricard** [comment]
Hi, sorry for the delay. The URL has been added, thanks!
