### ISSUE TITLE
Issue with phrasing of question -- cannot assign homework for class :(

### ISSUE THREAD

**Issue by jaanli** [signalstickers/signalstickers#907]
Hi! 

Can you please change the phrasing of this question in the submission form? 

`Is your pack original? Did the author of the pack draw it exclusively for Signal, from original artworks?`

(This wording does not account for works derived from creative commons licensed drawings or icons -- e.g. healthicons.org)

Context: I started a nonprofit based on signal.org, focused on open source AI for health, education, and discourse. I teach a large class at University of Tartu (https://courses.cs.ut.ee/2023/chatGPT/spring) and University of Pennsylvania and want to assign creation of a sticker pack and submission to signalstickers.ocm as homework to the 150+ students on the list.

We cannot hire artists to draw packs, but need sticker packs to empower our users. We use things like healthicons.org to help communicate, as well as other tools for communicating complex medical concepts in accessible visual language.

If this is a legal requirement, please add text specifying which country's copyright law requires this. 

Thank you!
Jaan

**Comment by romainricard** [comment]
Hi!
The "Original" field has nothing to do with copyright. We only use it do to highlight packs that are exclusive to Signal, or directly created by artists. 

![image](https://user-images.githubusercontent.com/7778898/232749942-74abf083-3306-4a72-9a4e-806a05043e4a.png)
![image](https://user-images.githubusercontent.com/7778898/232750010-5b50d44c-ff7c-4c16-beb3-257fe68b588e.png)
