### ISSUE TITLE
Cannot contribute newly created packs due to ['Pack does not exists on Signal: wrong id or key?'] error message

### ISSUE THREAD

**Issue by u00101010** [signalstickers/signalstickers#908]
Hey there!

Signal changed the way pack links look a couple months ago and got significantly shorter. These new links, however, do not work with the Signal Stickers website.

If I try to add them, I get the error message 

`['Pack does not exists on Signal: wrong id or key?']`

even though I'm using the only link that I got from the sticker creator, and using the in-app Share method to get a link provides the exact same one, too. Is there a way to get a link that works with the site, or is this an internal issue? The links work with the Signal Desktop and iOS app too just fine.

Example link:
https://signal.art/addstickers/#pack_id=ee7b01e49746373fa3a5d27ffcb2ce0e&pack_key=32ae1af950affde1be1a7afe44838edec60d20d462af449540ac532efcb1726d

**Comment by romainricard** [comment]
Thanks for the Issue. It does not seems that the format has changed, but there was another issue, which we periodically have. It has been fixed, you should be able to contribute now.
