### ISSUE TITLE
Removal Request (Hatred Promoting Material)

### ISSUE THREAD

**Issue by Worst-End-User** [signalstickers/signalstickers#913]
**Name**: _Evil Minds_ 
**URL**: https://sticker201.github.io/signalstickers/pack/dea992dbc049e6bdfd23a9635040873c
**Description**: A sticker pack that contains illustrations of people (for lack of a worse word) who have committed historically documented violent acts against humans.
**Argument**: Due to the documented acts of crime that the depicted figures have committed, these stickers can be viewed as promotion of hatred. As per stated in the guidelines, this is against the rules. Furthermore, there is a single sticker depicting a person making  suicidal gesture- a gun against the head. Worse, it actually is a documented moment, as it was carried out in real life.

// I’m trying to be as objectively neutral as possible here. But seriously these scumbags deserve no space anywhere whatsoever. I get the dark humour thing, I do- but not like this. This is not dark humour, it pushes way past that. If you’re angry and want to represent it, a mad hitler sticker is just… no. And most of these individual carried out mass acts of violence based on ethnicity, class, gender, so on. 

Many thanks for maintaining a resource that promotes the usage of a wonderful thing :)

**Comment by romainricard** [comment]
I see your points. Thanks for the reporting, removed.
