### ISSUE TITLE
Can't contribute sticker packs

### ISSUE THREAD

**Issue by Volki-57** [signalstickers/signalstickers#914]
When I click 'Propose to signalstickers.com' I get the error `['Pack does not exists on Signal: wrong id or key?']` and if I click it again I get `Invalid contribution request. Try again.` I tried both with Firefox and Chromium result is the same.

**Comment by romainricard** [comment]
`['Pack does not exists on Signal: wrong id or key?']` means that the URL (`signal.art/...`) is wrong. Did you manage to contribute?

**Comment by Volki-57** [comment]
Nope. I verified that URL is correct and working but same thing still happens.

![Ekran Görüntüsü - 2024-02-26 14-14-04](https://github.com/signalstickers/signalstickers/assets/49953945/8f1d563a-acab-406b-854a-1909f5e70602)
![Ekran Görüntüsü - 2024-02-26 14-13-59](https://github.com/signalstickers/signalstickers/assets/49953945/ce43997d-16d6-4f8e-b875-c7e909c2d798)

**Comment by romainricard** [comment]
The contribution feature works for me.
Can you give more details?
- Browser and browser version
- URL of the pack
- Special context you can think of (browser extension, etc...)

**Comment by Volki-57** [comment]
I use Librewolf 123.0 but I just also tried with Chromium 122.0.6261.69. Result was the same.

When I check the network logs from both browsers, I can see that PUT request to `https://api.signalstickers.com/v1/contribute/` returns status code 400. It is probably related.

![Ekran Görüntüsü - 2024-02-27 00-19-43](https://github.com/signalstickers/signalstickers/assets/49953945/a801975e-9696-49e6-b238-04e63d85f701)

Here is the URL of the pack: https://signal.art/addstickers/#pack_id=9d43e1eeaed78f568ef89b3d6530ad6e&pack_key=1940946b10c5ff338d1a5940f9b333796620bdc308045f3d35b8cb0fc4fe6cf4

I have ublock origin installed in both browsers but disabling it had no effect.

**Comment by romainricard** [comment]
So the problem is with this pack, the last sticker is invalid.  
![image](https://github.com/signalstickers/signalstickers/assets/7778898/e3f3983c-e69e-4266-9d91-5c3a8a284c12)

`signalstickers.com` uses [signalstickers-client](https://github.com/signalstickers/signalstickers-client) internally, and requires a valid pack. The lib fails to fetch the pack:

```
Traceback (most recent call last):
...
  File "signalstickers_client/stickersclient.py", line 52, in get_pack
    return await downloader.get_pack(self.http, pack_id, pack_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "signalstickers_client/classes/downloader.py", line 25, in get_pack
    async with anyio.create_task_group() as tg:
  File ".venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "signalstickers_client/classes/downloader.py", line 23, in get_sticker_image
    sticker.image_data = await get_sticker(http, sticker.id, pack_id, pack_key)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "signalstickers_client/classes/downloader.py", line 83, in get_sticker
    raise NotFound(sticker_resp, "Sticker not found")
signalstickers_client.errors.NotFound: 403: Sticker not found
```

Try to rebuild the pack or create another one!
