### ISSUE TITLE
Can we know the number of downloads of a sticker pack?

### ISSUE THREAD

**Issue by uT27SB8Ju** [signalstickers/signalstickers#918]
I uploaded a sticker pack and I would like to know how many people downloaded it. Sorry if this issue is missplaced.

**Comment by romainricard** [comment]
Hi, I just added this feature to signalstickers.
- views since last month + total views
- Number of stickers in the pack is now at the bottom

![image](https://github.com/signalstickers/signalstickers/assets/7778898/51a785e0-afed-423a-abb0-e3e6a003d1b2)

Thanks for the suggestion, cheers!
