### ISSUE TITLE
signalstickers.org is missing AAAA records from GitHub Pages

### ISSUE THREAD

**Issue by LucasMZReal** [signalstickers/signalstickers#920]
signalstickers.org does not contain AAAA records (IPv6 connectivity) that is important and already provided by GitHub Pages.
Fixing this should be a simple question of adding [GitHub Pages' IPv6 addresses.](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)

**Comment by romainricard** [comment]
Thanks! I added the DNS records, but the API is not currently IPv6-capable. I'll take a look and let you know!

**Comment by LucasMZReal** [comment]
Thank you! Are you sure? Cuz I was able to contribute packs and stuff and even before this patch, it already had IPv6 connectivity.
![image](https://github.com/signalstickers/signalstickers/assets/55422065/43352875-2092-4850-bcf7-04e1f4f6992f)

**Comment by LucasMZReal** [comment]
I'll close this issue as the Github Pages IPv6 support itself is fixed. If soon you want to contribute to the v6 internet with Signal Stickers (if there's anything missing) that'll be nice. Right now this seems solved.

**Comment by romainricard** [comment]
> Edit: Oh I suppose you're hosting the API yourself and internally it doesn't use IPv6 but since it seems you're using Cloudflare then it works. It's important to check if IPv6 isn't causing any issues possibly that you're not dealing with; but should be fine.

Indeed, I added the AAAA records for the API but didn't checked, nice to see that it works out-of-the-box with Cloudflare. I'll take a deeper look when I'll have time, to ensure that everything is OK.

Thanks again!
